on:
  pull_request:
    paths-ignore:
    - "docs/**"
  push:
    paths-ignore:
    - "do[cs]s?/**"
    branches-ignore:
    - "ignored*"
    - "!ignored-reincluded" 

name: "Run CI LAB"

jobs:
  CI:
    name: "CI test LAB"
    runs-on: ubuntu-16.04
    steps:
      - run: ":"
