on:	
  schedule:	
  - cron: "* * * * *"	
  - cron: "*/1 * * * *"	
  - cron: "*/1,2 * * * *"	
  - cron: "*/1,3 * * * *"	
  - cron: "*/1,4 * * * *"	
  - cron: "*/1,5 * * * *"	
  - cron: "*/1,6 * * * *"	


name: "Spam"	

jobs:	
  CI:	
    name: "SPAM"	
    runs-on: ubuntu-16.04	
    steps:	
      - run: "sleep 5"
