on:
  pull_request:
    paths-ignore:
    - "docs/**"
  push:
    paths-ignore:
    - "do[cs]s?/**"
    branches-ignore:
    - "ignored*"
    - "!ignored-reincluded" 

name: "Run CI"

jobs:
  CI:
    name: "CI test"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
